### ISSUE TITLE
Logging not working when using a remote console

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [adriankumpf/logger-telegram-backend#12]
I'm a bit puzzled about this: if I release an app with `mix distillery.release` and start it with `_build/dev/rel/testapp/bin/testapp console`, `Logger.error("test")` will correctly result in the bot sending a message. If I connect to the very same app by `_build/dev/rel/testapp/bin/testapp remote_console`, `Logger.error("test")` will result in an error: 

```
[error] GenServer #PID<0.107.0> terminating
** (stop) {:EXIT, {{:badmatch, {:error, %Mint.TransportError{reason: :ssl_not_started}}}, [{LoggerTelegramBackend, :handle_event, 2, [file: 'lib/telegram_logger_backend.ex', line: 47]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 577]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 559]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 300]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
Last message: {:gen_event_EXIT, LoggerTelegramBackend, {:EXIT, {{:badmatch, {:error, %Mint.TransportError{reason: :ssl_not_started}}}, [{LoggerTelegramBackend, :handle_event, 2, [file: 'lib/telegram_logger_backend.ex', line: 47]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 577]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 559]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 300]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}
```

I tried to add `:ssl` to the extra_applications, to no avail. What could be the cause of such a behavior?

I attached a minimal app to test, just `mix distillery.release` and run it as I explained above

[testapp 2.zip](https://github.com/adriankumpf/logger-telegram-backend/files/3907200/testapp.2.zip)

Thanks!

**Comment by alessandrousseglioviretta** [comment]
adding `Application.ensure_all_started(:ssl)` in the `init` func in module `LoggerTelegramBackend` solves the problem, but I'm unsure whether it's a good solution.

**Comment by adriankumpf** [comment]
Interesting. I don't know yet what is causing this, but I would have expected adding `:ssl` to the extra_applications to work.

If I'm not mistaken, you are running it from the master branch? Do you get the same error message with the latest stable release from hex?

**Comment by alessandrousseglioviretta** [comment]
I'm using Mint, which is not supported yet by the official release. With the latest release + Hackney I'm getting an error message that I had issues understand, which prompted me to try out Mint instead.
